services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: board_user
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: board_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
